import React from 'react'

export default function page() {
    return (
        <div>
            <span className='font-bold'>AC & Heating (HVAC) -</span> AC Compressor, AC Condenser, AC Condenser Cooling Fan, AC Controls, AC Evaporator, AC Evaporator Housing, AC Selector, Blower Motor, Heater Controls, Heater Core, Temperature Controls<br />
            <span className='font-bold'>Airbag & Safety System -</span> Air Bag Assembly, Air Bag Control Module, Air Bag Detector, Seat Belt, Seat Belt Motor, Seat Belt Track<br />
            <span className='font-bold'>Air Intake / Engine Air System - </span>Air Cleaner Assembly, Air Flow Meter<br />
            <span className='font-bold'>Exhaust & Emission System - </span>Air Injection Pump, Catalytic Convertor, Exhaust Manifold, Oxygen Sensor<br />
            <span className='font-bold'>Suspension & Steering Parts -</span> Air Ride Compressor, Air Ride Control Module, Coil Spring (Front), Coil Spring (Rear), Knee Assembly, Knuckle (Front), Leaf Spring (Front), Leaf Spring (Rear), Lower Control Arm (Front), Lower Control Arm (Rear), Power Steering Box, Power Steering Control Module, Power Steering Control Valve, Power Steering Pump, Shock Absorber, Spindle (Front), Steering Box, Steering Column, Steering Rack, Strut Assembly (Front), Strut Assembly (Rear), Suspension Assembly (Rear, Independent), Suspension Control Module, Suspension Crossmember (K-Frame), Torsion Bar, Trailing Arm, Upper Control Arm (Front), Upper Control Arm (Rear), Toe Arms, Suspension<br />
            <span className='font-bold'>Filters (Air, Oil, Fuel, Cabin) -</span> Air Filter<br />
            <span className='font-bold'>Electrical & Electronics -</span> Alternator, Anti-Theft Control Module, Battery, Body Control Module (BCM), Column Switch, Convertible Top Motor, Decklid Pull Down Motor, Door Lock Control Module, Door Motor (Power Slider|Tailgate), Door Switch, Door Vent Glass Regulator (Front), Door Window Control Module, Door Window Motor (Front), Door Window Motor (Rear), Engine Wiring Harness, Fuse Box, Headlight Motor, Headlight Switch (Auto Headlamps), Horn, Quarter Window Regulator (Rear), Relay (Electrical), Security System Control Module, Starter, Sunroof Motor, Tailgate Window Regulator, Transfer Case Shift Motor (Electric Shift), Voltage Regulator, Washer Motor (Front), Washer Motor (Rear), Wiper Motor (Front), Wiper Motor (Rear), Wiper Transmission<br />
            <span className='font-bold'>Interior Parts & Comfort -</span> Antenna (Electric), Antenna (Manual), Cassette Player, CD Changer, CD Player, Clock, Column Shift Lever, Console, Dashboard Assembly, Dashboard Pad, Door Handle (Inside), Glove Box, GPS Screen, Heads Up Display, Information Panel, Instrument Cluster (Speedometer), Owner's Manual, Radio, Seat (3rd Row or Bed), Seat (Front), Seat (Rear or 2nd Row), Seat Control Module, Seat Track (Front), Speaker, Speedometer Cluster, Steering Wheel, Sun Visor, Sunroof Assembly<br />
            <span className='font-bold'>Brakes & ABS Parts - </span>Anti-Lock Brake Control Module (ABS), Brake Booster, Brake Pads, Caliper, Master Cylinder, Master Cylinder (Brake), Proportioning Valve (Brake), Rotor (Brake, Front), Rotor (Brake, Rear)<br />
            <span className='font-bold'>Transmission & Drivetrain - </span>Axle Assembly, Axle Assembly (Front, 4WD), Axle Assembly (Rear), Axle Beam (Front, 2WD), Axle Beam (Rear, FWD, Complete), Axle Shaft, Bell Housing, Carrier Assembly, Differential Assembly (Front), Differential Assembly (Rear), Differential Case, Drive Shaft (Front), Drive Shaft (Rear), Flywheel, Gearbox, Master Cylinder (Clutch), Oil Pan (Transmission), Ring Gear and Pinion, Shifter Assembly (Floor), Slave Cylinder (Clutch), Stub Axle (Rear), Transfer Case Adapter, Transfer Case Assembly, Transfer Case Control Module, Transmission Assembly, Transmission Control Module, Transmission Torque Converter<br />
            <span className='font-bold'>Glass & Mirrors -</span> Back Glass, Door Glass (Front), Door Glass (Rear), Door Vent Glass (Front), Door Vent Glass (Rear), Hatchback Glass, Mirror (Rear View), Mirror (Side View, Electric), Mirror (Side View, Manual), Quarter Glass, Roof Glass, Sunroof Glass, Tailgate Glass, Windshield<br />
            <span className='font-bold'>Lighting & Lamps -</span> Backup Light, Cornering Light, Driving Light, Fog Light, Headlight Assembly, Headlight Bezel|Door, Headlight Control Module, Marker Light (Front), Marker Light (Rear), Parklight, Reverse Light, Taillight, Third Brake Light, Turn Signal Light<br />
            <span className='font-bold'>Body Kits -</span> Bed (Pickup), Bumper Assembly (Front), Bumper Assembly (Rear), Bumper Cover (Front), Bumper Cover (Rear), Bumper Shock, Cab Clip, Convertible Top, Cowl, Decklid, Door Assembly (Front), Door Assembly (Rear or Back), Door Handle (Outside), Door Window Regulator (Front), Door Window Regulator (Rear), Fender (Front), Fender (Rear), Frame (Complete), Frame (Front), Front End Assembly (Nose), Fuel Door, Grille, Hard Top, Hatchback, Header Panel Assembly, Hood, Hood Hinge, Hood Piston|Strut, Jack, Mud Flaps, Nose (Front End Assembly), Pickup Bed, Pickup Cap|Topper, Quarter Panel Assembly, Radiator Support, Rear Clip, Rocker Panel, Roll Bar, Roof Assembly, Roof Rack, Running Board, Soft Top, Spare Tire Carrier, Spoiler (Front), Spoiler (Rear), Tailgate, Trailer Hitch, T-Top, Valance (Front), Valance (Rear), Washer Fluid Reservoir, Wiper Arm, Bonnet, Fender Liner<br />
            <span className='font-bold'>Belts & Timing Components -</span> Belt Tensioner, Timing Cover<br />
            <span className='font-bold'>Engine Parts -</span> Camshaft, Carburetor, Crankshaft, Cylinder Block, Cylinder Head, Engine Assembly, Engine Block, Engine Mount, Harmonic Balancer (Crank Pulley), Intake Manifold, Oil Pan (Engine), Oil Pump, Piston, Supercharger, Throttle Body Assembly, Turbocharger, Vacuum Pump, Valve Cover<br />
            <span className='font-bold'>Sensors & Control Modules - </span>Chassis Control Module, Computer (ECU, ECM), Control Module, Cruise Control Module, Engine Control Module (ECU, ECM), GPS Control Module, Keyless Entry Control Module, Mass Air Flow Sensor, Multi-Function Control Module, Navigation Control Module, Temperature Control Module, Traction Control Module<br />
            <span className='font-bold'>Ignition Parts - </span>Coil (Ignition), Distributor, Ignition Control Module, Ignition Switch, Spark Plug<br />
            <span className='font-bold'>Cooling System -</span> Coolant Reservoir, Cooling Fans Assembly (Rad. & Cond.), Engine Oil Cooler, Fan Blade, Fan Clutch, Fan Control Module, Intercooler, Radiator, Radiator Cooling Fan, Radiator Shroud, Water Pump<br />
            <span className='font-bold'>Fuel System -</span> Fuel Injection Pump, Fuel Pump, Fuel Sending Unit, Fuel Tank<br />
            <span className='font-bold'>Wheels, Tires & Hub Parts -</span> Hub, Hub Cap (Wheel Cover), Rim, Spare Tire (with Rim), Tire, Wheel, Wheel Cover (Hub Cap)</div>
    )
}
